camunda.bpm:
  admin-user:
    id: demo
    password: 123
  webapp:
    application-path: camunda-web
  history-level: full
  process-engine-name: default
  job-execution.active: true
# database.schema-update: true
